// SPDX-License-Identifier: MPL-2.0
// (c) Hare authors <https://harelang.org>
//
// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

def K: size = 3;

// The size of a ciphertext produced by ML-KEM-768.
export def CT768SZ: size = 1088;

// The size of an ML-KEM-768 encapsulation key.
export def EK768SZ: size = 1184;
