 // Generated by protogen, do not edit
.extern sys.call_generic
.extern sys.recv_error
.extern sys.recv_enosys
.extern sys.recv_dispatch
.set SYS_call,		6
.set SYS_recv,		7
.set SYS_reply,		8
.set ID_system_mman,	0xfd958400
.set NFUNC_system_mman,	4
.set proto_server_sz,   224	/* size(proto::server) */

.section ".text.proto.system._recv_mman","ax"
.type proto.system._recv_mman,@function
.global proto.system._recv_mman
proto.system._recv_mman:
	endbr64
	subq $24, %rsp
	movq %rsi, 0(%rsp)	/* serv: *proto::system::mman_server */

	mov $SYS_recv, %rax
	syscall
	cmp $0, %al
	jne sys.recv_error
	shrq $8, %rax
	movq %rax, 16(%rsp)		/* caller flags */

	movq %rdi, 8(%rsp)		/* badge + user word */
	shrq $(32 + 8), %rdi
	shlq $8, %rdi			/* 24-bit protocol ID */
	movq 0(%rsp), %r11
	addq $proto_server_sz, %r11	/* &serv.vtable */

	movq $ID_system_mman, %rax
	cmpq %rax, %rdi
	je proto.system._recv_mman.dispatch

	jmp sys.recv_enosys

.section ".text.proto.system._recv_mman.dispatch","ax"
.type proto.system._recv_mman.dispatch,@function
.global proto.system._recv_mman.dispatch
proto.system._recv_mman.dispatch:
	endbr64
	movq (%r11), %rax	/* %rax: proto::system::mman_vtable */
	movq 8(%rsp), %rdi
	shrq $32, %rdi
	andq $0xFF, %rdi	/* 8-bit function number */
	cmpq $NFUNC_system_mman, %rdi
	jge sys.recv_enosys
	jmp sys.recv_dispatch


.section ".text.proto.system._mman_mmap","ax"
.type proto.system._mman_mmap,@function
.global proto.system._mman_mmap
proto.system._mman_mmap:
	movq $((ID_system_mman | 0) << 32), %rax
	jmp sys.call_generic


.section ".text.proto.system._mman_mmiomap","ax"
.type proto.system._mman_mmiomap,@function
.global proto.system._mman_mmiomap
proto.system._mman_mmiomap:
	movq $((ID_system_mman | 1) << 32), %rax
	jmp sys.callx_generic


.section ".text.proto.system._mman_munmap","ax"
.type proto.system._mman_munmap,@function
.global proto.system._mman_munmap
proto.system._mman_munmap:
	movq $((ID_system_mman | 2) << 32), %rax
	jmp sys.call_generic


.section ".text.proto.system._mman_mprotect","ax"
.type proto.system._mman_mprotect,@function
.global proto.system._mman_mprotect
proto.system._mman_mprotect:
	movq $((ID_system_mman | 3) << 32), %rax
	jmp sys.call_generic
