 // Generated by protogen, do not edit
.extern sys.call_generic
.extern sys.recv_error
.extern sys.recv_enosys
.extern sys.recv_dispatch
.extern proto.._recv_mman.dispatch
.set SYS_call,		6
.set SYS_recv,		7
.set SYS_reply,		8
.set ID_system_process,	0x1364a200
.set ID_system_mman,	0xfd958400
.set NFUNC_system_process,	2
.set proto_server_sz,   224	/* size(proto::server) */

.section ".text.proto.system._recv_process","ax"
.type proto.system._recv_process,@function
.global proto.system._recv_process
proto.system._recv_process:
	endbr64
	subq $24, %rsp
	movq %rsi, 0(%rsp)	/* serv: *proto::system::process_server */

	mov $SYS_recv, %rax
	syscall
	cmp $0, %al
	jne sys.recv_error
	shrq $8, %rax
	movq %rax, 16(%rsp)		/* caller flags */

	movq %rdi, 8(%rsp)		/* badge + user word */
	shrq $(32 + 8), %rdi
	shlq $8, %rdi			/* 24-bit protocol ID */
	movq 0(%rsp), %r11
	addq $proto_server_sz, %r11	/* &serv.vtable */

	movq $ID_system_process, %rax
	cmpq %rax, %rdi
	je proto.system._recv_process.dispatch
	addq $8, %r11
	movq $ID_system_mman, %rax
	cmpq %rax, %rdi
	je proto.system._recv_mman.dispatch

	jmp sys.recv_enosys

.section ".text.proto.system._recv_process.dispatch","ax"
.type proto.system._recv_process.dispatch,@function
.global proto.system._recv_process.dispatch
proto.system._recv_process.dispatch:
	endbr64
	movq (%r11), %rax	/* %rax: proto::system::process_vtable */
	movq 8(%rsp), %rdi
	shrq $32, %rdi
	andq $0xFF, %rdi	/* 8-bit function number */
	cmpq $NFUNC_system_process, %rdi
	jge sys.recv_enosys
	jmp sys.recv_dispatch


.section ".text.proto.system._process_exit","ax"
.type proto.system._process_exit,@function
.global proto.system._process_exit
proto.system._process_exit:
	movq $((ID_system_process | 0) << 32), %rax
	jmp sys.call_generic


.section ".text.proto.system._process_set_tls_base","ax"
.type proto.system._process_set_tls_base,@function
.global proto.system._process_set_tls_base
proto.system._process_set_tls_base:
	movq $((ID_system_process | 1) << 32), %rax
	jmp sys.call_generic
