 // Generated by protogen, do not edit
.extern sys.call_generic
.extern sys.recv_error
.extern sys.recv_enosys
.extern sys.recv_dispatch
.set SYS_call,		6
.set SYS_recv,		7
.set SYS_reply,		8
.set ID_io_file,	0x95628400
.set NFUNC_io_file,	6
.set proto_server_sz,   224	/* size(proto::server) */

.section ".text.proto.io._recv_file","ax"
.type proto.io._recv_file,@function
.global proto.io._recv_file
proto.io._recv_file:
	endbr64
	subq $24, %rsp
	movq %rsi, 0(%rsp)	/* serv: *proto::io::file_server */

	mov $SYS_recv, %rax
	syscall
	cmp $0, %al
	jne sys.recv_error
	shrq $8, %rax
	movq %rax, 16(%rsp)		/* caller flags */

	movq %rdi, 8(%rsp)		/* badge + user word */
	shrq $(32 + 8), %rdi
	shlq $8, %rdi			/* 24-bit protocol ID */
	movq 0(%rsp), %r11
	addq $proto_server_sz, %r11	/* &serv.vtable */

	movq $ID_io_file, %rax
	cmpq %rax, %rdi
	je proto.io._recv_file.dispatch

	jmp sys.recv_enosys

.section ".text.proto.io._recv_file.dispatch","ax"
.type proto.io._recv_file.dispatch,@function
.global proto.io._recv_file.dispatch
proto.io._recv_file.dispatch:
	endbr64
	movq (%r11), %rax	/* %rax: proto::io::file_vtable */
	movq 8(%rsp), %rdi
	shrq $32, %rdi
	andq $0xFF, %rdi	/* 8-bit function number */
	cmpq $NFUNC_io_file, %rdi
	jge sys.recv_enosys
	jmp sys.recv_dispatch


.section ".text.proto.io._file_read","ax"
.type proto.io._file_read,@function
.global proto.io._file_read
proto.io._file_read:
	movq $((ID_io_file | 0) << 32), %rax
	jmp sys.callx_generic


.section ".text.proto.io._file_write","ax"
.type proto.io._file_write,@function
.global proto.io._file_write
proto.io._file_write:
	movq $((ID_io_file | 1) << 32), %rax
	jmp sys.callx_generic


.section ".text.proto.io._file_seek","ax"
.type proto.io._file_seek,@function
.global proto.io._file_seek
proto.io._file_seek:
	movq $((ID_io_file | 2) << 32), %rax
	jmp sys.call_generic


.section ".text.proto.io._file_truncate","ax"
.type proto.io._file_truncate,@function
.global proto.io._file_truncate
proto.io._file_truncate:
	movq $((ID_io_file | 3) << 32), %rax
	jmp sys.call_generic


.section ".text.proto.io._file_pread","ax"
.type proto.io._file_pread,@function
.global proto.io._file_pread
proto.io._file_pread:
	movq $((ID_io_file | 4) << 32), %rax
	jmp sys.callx_generic


.section ".text.proto.io._file_pwrite","ax"
.type proto.io._file_pwrite,@function
.global proto.io._file_pwrite
proto.io._file_pwrite:
	movq $((ID_io_file | 5) << 32), %rax
	jmp sys.callx_generic
